### ISSUE TITLE
LV2 crate name

### ISSUE THREAD

**Issue by JOOpdenhoevel** [poidl/lv2#3]
We, this is me and some other people in the [RustAudio Organisation](https://github.com/RustAudio), are currently working on a LV2 plugin framework for Rust called [rust-lv2](https://github.com/RustAudio/rust-lv2). We have a proper, safe and rustic interface covering the core specification as well as URID, Atom, MIDI, Time and Units and support for State and Worker is in the works.

There are already some people who started to work with it and therefore, we would like to make a proper release to crates.io. Of course, the first and ideal name for this crate would be `lv2`, but it is already occupied by your project.

Since your crate isn't used that much, doesn't have that many features and isn't developed anymore, we would kindly ask you to transfer the ownership of that crate name to us. Do you agree with that?

**Comment by poidl** [comment]
Yes I agree.

 
I received a similar request by Adrien Prokopowicz last April.

 
What do I have to do to transfer ownership?

-----Original message-----
From: Jan-Oliver Opdenhövel
Sent: Wednesday, February 19 2020, 5:05 pm
To: poidl/lv2
Cc: Subscribed
Subject: [poidl/lv2] LV2 crate name (#3)

We, this is me and some other people in the RustAudio Organisation, are currently working on a LV2 plugin framework for Rust called rust-lv2. We have a proper, safe and rustic interface covering the core specification as well as URID, Atom, MIDI, Time and Units and support for State and Worker is in the works.

There are already some people who started to work with it and therefore, we would like to make a proper release to crates.io. Of course, the first and ideal name for this crate would be lv2, but it is already occupied by your project.

Since your crate isn't used that much, doesn't have that many features and isn't developed anymore, we would kindly ask you to transfer the ownership of that crate name to us. Do you agree with that?

**Comment by JOOpdenhoevel** [comment]
According to the documentation of [`cargo owner`](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner), you have to open a terminal in your `lv2` repository and run
```
cargo owner --add Janonard
```
This will make me a named owner, which allows me to add the [team of LV2 Maintainers](https://github.com/orgs/RustAudio/teams/lv2-maintainers) and remove you from the crate.

**Comment by poidl** [comment]
Done!

 
>cargo owner --add Janonard 
   Updating crates.io index 
      Owner user Janonard has been invited to be an owner of crate lv2
 
-----Original message-----

**Comment by JOOpdenhoevel** [comment]
It doesn't seem to have worked :confused: `cargo owner --iist` still only lists you.

**Comment by poidl** [comment]
Ok...I went to crates.io and didn't see anything under "pending invites", but I'm not sure if invites I send should show up there (or only those I received).

 
Maybe it takes time to update?

 
Anyway, I issued the command again (with the same output)

 
cargo owner --add Janonard 
   Updating crates.io index 
      Owner user Janonard has been invited to be an owner of crate lv2


 
-----Original message-----

**Comment by JOOpdenhoevel** [comment]
I'm sorry, but `crates.io` still used an old email I accidentally deleted. If you run it one more time, it should work...

**Comment by JOOpdenhoevel** [comment]
Oh, never mind! I found the invite on `crates.io`! Thank you!
